### ISSUE TITLE
Not consistent with Blog slides

### ISSUE THREAD

**Issue by djmorosini** [BurlingtonCodeAcademy/express-blog#1]
1) In the express-blog repo the "articles" directory is in the public directory but on the slides it is referenced as a top level directory("const articlesDir = $path.resolve('./articles');"). The express-blog repo should change to reflect this.

2) The express-blog repo contains unused files from the last classes project (lib/messages && lib/house && lib/room) that should be removed

**Comment by alexch** [comment]
I went to fix these and found that *I already had*... but then I neglected to `git commit` them! 😭
